(eval-when-compile    (require 'color-theme))
(defun my-color-theme ()
  "Color theme by U-BROADWAY\mmikhanosha, created 2021-05-28."
  (interactive)
  (color-theme-install
   '(my-color-theme
     ((background-color . "unspecified-bg")
      (background-mode . dark)
      (border-color . "black")
      (cursor-color . "black")
      (foreground-color . "#000000")
      (mouse-color . "#000000"))
     ((artbollocks-background-color . "White")
      (artbollocks-foreground-color . "Purple")
      (compilation-message-face . underline)
      (cua-global-mark-cursor-color . "cyan")
      (cua-normal-cursor-color . "red")
      (cua-overwrite-cursor-color . "yellow")
      (cua-read-only-cursor-color . "darkgreen")
      (erc-interpret-mirc-color . t)
      (font-lock-artbollocks-face . font-lock-artbollocks-face)
      (font-lock-lexical-illusions-face . font-lock-lexical-illusions-face)
      (font-lock-passive-voice-face . font-lock-passive-voice-face)
      (font-lock-weasel-words-face . font-lock-weasel-words-face)
      (hl-line-face . hl-line)
      (ispell-highlight-face . flyspell-incorrect)
      (lexical-illusions-background-color . "magenta")
      (lexical-illusions-foreground-color . "black")
      (list-matching-lines-buffer-name-face . underline)
      (list-matching-lines-current-line-face . lazy-highlight)
      (list-matching-lines-face . bold)
      (list-matching-lines-prefix-face . shadow)
      (org-goto-interface . outline)
      (passive-voice-background-color . "White")
      (passive-voice-foreground-color . "Gray")
      (tags-tag-face . default)
      (view-highlight-face . highlight)
      (vline-face . vline)
      (vline-visual-face . vline-visual)
      (weasel-words-background-color . "White")
      (weasel-words-foreground-color . "Brown")
      (widget-mouse-face . highlight))
     (default ((t (:stipple nil :background "unspecified-bg" :foreground "#000000" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 1 :width normal :foundry "default" :family "default"))))
     (CUA-global-mark-face ((t (:background "cyan" :foreground "black"))))
     (CUA-rectangle-face ((t (:background "maroon" :foreground "white"))))
     (CUA-rectangle-noselect-face ((t (:background "dimgray" :foreground "white"))))
     (Info-quoted ((t (:inherit fixed-pitch-serif))))
     (Man-overstrike ((t (:inherit bold))))
     (Man-reverse ((t (:inherit highlight))))
     (Man-underline ((t (:inherit underline))))
     (action-lock-face ((t (:underline t))))
     (bg:erc-color-face0 ((t (:background "White"))))
     (bg:erc-color-face1 ((t (:background "black"))))
     (bg:erc-color-face10 ((t (:background "lightblue1"))))
     (bg:erc-color-face11 ((t (:background "cyan"))))
     (bg:erc-color-face12 ((t (:background "blue"))))
     (bg:erc-color-face13 ((t (:background "deeppink"))))
     (bg:erc-color-face14 ((t (:background "gray50"))))
     (bg:erc-color-face15 ((t (:background "gray90"))))
     (bg:erc-color-face2 ((t (:background "blue4"))))
     (bg:erc-color-face3 ((t (:background "green4"))))
     (bg:erc-color-face4 ((t (:background "red"))))
     (bg:erc-color-face5 ((t (:background "brown"))))
     (bg:erc-color-face6 ((t (:background "purple"))))
     (bg:erc-color-face7 ((t (:background "orange"))))
     (bg:erc-color-face8 ((t (:background "yellow"))))
     (bg:erc-color-face9 ((t (:background "green"))))
     (bmkp-*-mark ((t (:background "Yellow" :foreground "Red"))))
     (bmkp->-mark ((t (:foreground "Blue"))))
     (bmkp-D-mark ((t (:background "Red" :foreground "Yellow"))))
     (bmkp-X-mark ((t (:foreground "Red"))))
     (bmkp-a-mark ((t (:background "SkyBlue"))))
     (bmkp-bad-bookmark ((t (:background "Chartreuse1" :foreground "Red"))))
     (bmkp-bookmark-file ((t (:background "DarkGreen" :foreground "Orange"))))
     (bmkp-bookmark-list ((t (:background "LightGray" :foreground "DarkRed"))))
     (bmkp-buffer ((t (:foreground "DarkGreen"))))
     (bmkp-desktop ((t (:background "PaleGoldenrod" :foreground "DarkBlue"))))
     (bmkp-file-handler ((t (:background "Thistle"))))
     (bmkp-function ((t (:foreground "DeepPink1"))))
     (bmkp-gnus ((t (:foreground "DarkBlue"))))
     (bmkp-heading ((t (:foreground "Blue"))))
     (bmkp-info ((t (:foreground "DarkRed"))))
     (bmkp-local-directory ((t (:background "HoneyDew2" :foreground "DarkBlue"))))
     (bmkp-local-file-with-region ((t (:foreground "Blue"))))
     (bmkp-local-file-without-region ((t (:foreground "Black"))))
     (bmkp-man ((t (:foreground "Orange4"))))
     (bmkp-mode-line-flagged ((t (:foreground "Red"))))
     (bmkp-mode-line-marked ((t (:inherit (quote bmkp->-mark)))))
     (bmkp-no-local ((t (:foreground "gray60"))))
     (bmkp-non-file ((t (:foreground "gray60"))))
     (bmkp-remote-file ((t (:foreground "DarkViolet"))))
     (bmkp-sequence ((t (:foreground "DarkOrange2"))))
     (bmkp-su-or-sudo ((t (:foreground "Red"))))
     (bmkp-t-mark ((t (:foreground "Red"))))
     (bmkp-url ((t (:foreground "DarkMagenta"))))
     (bmkp-variable-list ((t (:foreground "DarkCyan"))))
     (bold ((t (:bold t :weight bold))))
     (bold-italic ((t (:italic t :bold t :slant italic :weight bold))))
     (bookmark-menu-bookmark ((t (:bold t :weight bold))))
     (bookmark-menu-heading ((t (:bold t :foreground "ForestGreen" :weight bold))))
     (border ((t (:background "black"))))
     (buffer-menu-buffer ((t (:bold t :weight bold))))
     (button ((t (:underline t))))
     (c-annotation-face ((t (:inherit font-lock-constant-face))))
     (c-nonbreakable-space-face ((t (:bold t :background "Red" :weight bold))))
     (calendar-month-header ((t (:inherit font-lock-function-name-face))))
     (calendar-today ((t (:underline t))))
     (calendar-weekday-header ((t (:inherit font-lock-constant-face))))
     (calendar-weekend-header ((t (:inherit font-lock-comment-face))))
     (change-log-acknowledgement ((t (:foreground "blue"))))
     (change-log-conditionals ((t (:foreground "#008b8b"))))
     (change-log-date ((t (:background "#f2f2f2" :foreground "#ff00ff"))))
     (change-log-email ((t (:foreground "#008b8b"))))
     (change-log-file ((t (:foreground "#008b8b"))))
     (change-log-function ((t (:foreground "#008b8b"))))
     (change-log-list ((t (:bold t :foreground "#a52a2a" :weight bold))))
     (change-log-name ((t (:foreground "green4"))))
     (col-highlight ((t (:background "SlateGray3"))))
     (comint-highlight-input ((t (:bold t :weight bold))))
     (comint-highlight-prompt ((t (:foreground "dark blue"))))
     (compilation-column-number ((t (:bold t :foreground "ForestGreen" :weight bold))))
     (compilation-error ((t (:bold t :foreground "Red" :weight bold))))
     (compilation-info ((t (:bold t :foreground "Green3" :weight bold))))
     (compilation-line-number ((t (:foreground "#008b8b"))))
     (compilation-mode-line-exit ((t (:bold t :inherit compilation-info :foreground "ForestGreen" :weight bold))))
     (compilation-mode-line-fail ((t (:bold t :inherit compilation-error :foreground "Red1" :weight bold))))
     (compilation-mode-line-run ((t (:inherit compilation-warning))))
     (compilation-warning ((t (:bold t :foreground "Orange" :weight bold))))
     (completions-annotations ((t (:italic t :slant italic))))
     (completions-common-part ((t (nil))))
     (completions-first-difference ((t (nil))))
     (cperl-array-face ((t (:foreground "brown"))))
     (cperl-hash-face ((t (:foreground "red"))))
     (cperl-nonoverridable-face ((t (:foreground "#008b8b"))))
     (cua-global-mark ((t (:background "yellow1" :foreground "black"))))
     (cua-rectangle ((t (:background "maroon" :foreground "white"))))
     (cua-rectangle-noselect ((t (:background "dimgray" :foreground "white"))))
     (cursor ((t (:background "#000000"))))
     (custom-button ((t (:background "lightgrey" :foreground "black" :box (:line-width 2 :style released-button)))))
     (custom-button-mouse ((t (:background "grey90" :foreground "black" :box (:line-width 2 :style released-button)))))
     (custom-button-pressed ((t (:background "lightgrey" :foreground "black" :box (:line-width 2 :style pressed-button)))))
     (custom-button-pressed-unraised ((t (:foreground "magenta4" :underline t))))
     (custom-button-unraised ((t (:underline t))))
     (custom-changed ((t (:background "blue1" :foreground "white"))))
     (custom-comment ((t (:background "gray85"))))
     (custom-comment-tag ((t (:foreground "blue4"))))
     (custom-documentation ((t (nil))))
     (custom-face-tag ((t (:bold t :weight bold :height 1.1))))
     (custom-group-subtitle ((t (:bold t :weight bold))))
     (custom-group-tag ((t (:bold t :foreground "blue1" :weight bold :height 1.1))))
     (custom-group-tag-1 ((t (:bold t :foreground "red1" :weight bold :height 1.1))))
     (custom-invalid ((t (:background "red1" :foreground "yellow1"))))
     (custom-link ((t (:foreground "blue1" :underline t))))
     (custom-modified ((t (:background "blue1" :foreground "white"))))
     (custom-rogue ((t (:background "black" :foreground "pink"))))
     (custom-saved ((t (:underline t))))
     (custom-set ((t (:background "white" :foreground "blue1"))))
     (custom-state ((t (:foreground "dark green"))))
     (custom-themed ((t (:background "blue1" :foreground "white"))))
     (custom-variable-button ((t (:bold t :underline t :weight bold))))
     (custom-variable-tag ((t (:bold t :foreground "blue1" :weight bold :height 1.1))))
     (custom-visibility ((t (:foreground "blue1" :underline t :height 0.8))))
     (diary ((t (:foreground "red1"))))
     (diary-anniversary ((t (:bold t :foreground "#a52a2a" :weight bold))))
     (diary-button ((t (nil))))
     (diary-time ((t (:foreground "#008b8b"))))
     (diff-added ((t (nil))))
     (diff-changed ((t (nil))))
     (diff-context ((t (:foreground "grey50"))))
     (diff-file-header ((t (:bold t :background "grey70" :weight bold))))
     (diff-function ((t (:background "grey80"))))
     (diff-header ((t (:background "grey80"))))
     (diff-hunk-header ((t (:background "grey80"))))
     (diff-index ((t (:bold t :background "grey70" :weight bold))))
     (diff-indicator-added ((t (nil))))
     (diff-indicator-changed ((t (nil))))
     (diff-indicator-removed ((t (nil))))
     (diff-nonexistent ((t (:bold t :background "grey70" :weight bold))))
     (diff-refine-added ((t (:inherit diff-refine-changed :background "#22aa22"))))
     (diff-refine-change ((t (:background "grey85"))))
     (diff-refine-changed ((t (:background "#aaaa22"))))
     (diff-refine-removed ((t (:inherit diff-refine-changed :background "#aa2222"))))
     (diff-removed ((t (nil))))
     (dired-directory ((t (:foreground "#008b8b"))))
     (dired-flagged ((t (:bold t :foreground "Red" :weight bold))))
     (dired-header ((t (:bold t :foreground "ForestGreen" :weight bold))))
     (dired-ignored ((t (:foreground "grey50"))))
     (dired-mark ((t (:foreground "green4"))))
     (dired-marked ((t (:bold t :foreground "Red" :weight bold))))
     (dired-perm-write ((t (:foreground "blue"))))
     (dired-symlink ((t (:bold t :foreground "#a52a2a" :weight bold))))
     (dired-warning ((t (:foreground "blue"))))
     (diredp-compressed-file-suffix ((t (:foreground "Yellow"))))
     (diredp-date-time ((t (:foreground "DarkGoldenrod4"))))
     (diredp-deletion ((t (:background "Red" :foreground "Yellow"))))
     (diredp-deletion-file-name ((t (:foreground "Red"))))
     (diredp-dir-heading ((t (:background "Pink" :foreground "Blue"))))
     (diredp-dir-priv ((t (:background "LightGray" :foreground "DarkRed"))))
     (diredp-display-msg ((t (:foreground "Blue"))))
     (diredp-exec-priv ((t (:background "LightSteelBlue"))))
     (diredp-executable-tag ((t (:foreground "Red"))))
     (diredp-file-name ((t (:foreground "Blue"))))
     (diredp-file-suffix ((t (:foreground "DarkMagenta"))))
     (diredp-flag-mark ((t (:background "Blueviolet" :foreground "Yellow"))))
     (diredp-flag-mark-line ((t (:background "Skyblue"))))
     (diredp-ignored-file-name ((t (:foreground "#00006DE06DE0"))))
     (diredp-link-priv ((t (:foreground "DarkOrange"))))
     (diredp-mode-line-flagged ((t (:foreground "Red"))))
     (diredp-mode-line-marked ((t (:foreground "DarkViolet"))))
     (diredp-no-priv ((t (:background "LightGray"))))
     (diredp-number ((t (:foreground "DarkBlue"))))
     (diredp-other-priv ((t (:background "PaleGoldenrod"))))
     (diredp-rare-priv ((t (:background "SpringGreen" :foreground "Magenta"))))
     (diredp-read-priv ((t (:background "MediumAquamarine"))))
     (diredp-symlink ((t (:foreground "DarkOrange"))))
     (diredp-write-priv ((t (:background "Orchid"))))
     (doremi-last-face ((t (nil))))
     (ebrowse-default ((t (nil))))
     (ebrowse-file-name ((t (:italic t :slant italic))))
     (ebrowse-member-attribute ((t (:foreground "red1"))))
     (ebrowse-member-class ((t (:foreground "purple"))))
     (ebrowse-progress ((t (:background "blue1"))))
     (ebrowse-root-class ((t (:bold t :foreground "blue1" :weight bold))))
     (ebrowse-tree-mark ((t (:foreground "red1"))))
     (ediff-current-diff-A ((t (:background "#afd7d7"))))
     (ediff-current-diff-Ancestor ((t (:background "magenta3" :foreground "black"))))
     (ediff-current-diff-B ((t (:background "#afd7ff"))))
     (ediff-current-diff-C ((t (:background "#d7d7ff"))))
     (ediff-even-diff-A ((t (:bold t :background "light grey" :foreground "red3" :weight bold))))
     (ediff-even-diff-Ancestor ((t (:bold t :background "light grey" :foreground "cyan3" :weight bold))))
     (ediff-even-diff-B ((t (:bold t :background "Grey" :foreground "blue3" :weight bold))))
     (ediff-even-diff-C ((t (:bold t :background "light grey" :foreground "yellow3" :weight bold))))
     (ediff-fine-diff-A ((t (:bold t :background "sky blue" :foreground "white" :weight bold))))
     (ediff-fine-diff-Ancestor ((t (:background "green" :foreground "red3"))))
     (ediff-fine-diff-B ((t (:background "cyan3" :foreground "magenta3"))))
     (ediff-fine-diff-C ((t (:bold t :background "#afd7d7" :foreground "yellow3" :weight bold))))
     (ediff-odd-diff-A ((t (:bold t :background "black" :foreground "red3" :weight bold))))
     (ediff-odd-diff-Ancestor ((t (:bold t :background "black" :foreground "green3" :weight bold))))
     (ediff-odd-diff-B ((t (:bold t :background "black" :foreground "cyan3" :weight bold))))
     (ediff-odd-diff-C ((t (:bold t :background "black" :foreground "yellow3" :weight bold))))
     (egg-an-tag-mono ((t (:bold t :foreground "DarkGoldenRod" :weight bold))))
     (egg-blame ((t (:foreground "black"))))
     (egg-blame-culprit ((t (:background "grey85" :foreground "grey35" :height 1.05))))
     (egg-blame-subject ((t (:background "grey85" :foreground "black" :height 1.05))))
     (egg-branch ((t (:bold t :foreground "SkyBlue" :weight bold :height 1.05))))
     (egg-branch-mono ((t (:bold t :foreground "SkyBlue" :weight bold))))
     (egg-diff-add ((t (:foreground "blue1"))))
     (egg-diff-conflict ((t (:foreground "Blue"))))
     (egg-diff-del ((t (:foreground "red"))))
     (egg-diff-file-header ((t (:bold t :foreground "SlateBlue" :weight bold :height 1.05))))
     (egg-diff-hunk-header ((t (:background "grey85"))))
     (egg-diff-none ((t (:foreground "grey50"))))
     (egg-electrict-choice ((t (:bold t :foreground "Blue" :weight bold))))
     (egg-graph ((t (:foreground "grey90"))))
     (egg-header ((t (:bold t :weight bold :height 1.05))))
     (egg-help-header-1 ((t (:bold t :foreground "navy" :weight bold))))
     (egg-help-header-2 ((t (:foreground "Black" :height 0.9))))
     (egg-help-key ((t (:foreground "gray" :height 0.9))))
     (egg-log-HEAD ((t (:background "lightgoldenrod2"))))
     (egg-log-buffer-mark ((t (:bold t :foreground "black" :weight bold))))
     (egg-remote-mono ((t (:bold t :foreground "Orchid" :weight bold))))
     (egg-section-title ((t (:bold t :foreground "DarkGoldenrod" :weight bold :height 1.05))))
     (egg-stash-mono ((t (:bold t :foreground "DarkGoldenRod" :weight bold))))
     (egg-tag-mono ((t (:bold t :foreground "GoldenRod" :weight bold))))
     (egg-term ((t (:bold t :foreground "SkyBlue" :weight bold))))
     (egg-text-1 ((t (:foreground "navy"))))
     (egg-text-2 ((t (:foreground "navy" :height 1.05))))
     (egg-text-3 ((t (:foreground "navy" :height 1.1))))
     (egg-text-4 ((t (:foreground "navy" :height 1.15))))
     (egg-text-base ((t (:foreground "navy"))))
     (egg-text-help ((t (:foreground "navy" :height 0.8))))
     (egg-unmerged-diff-file-header ((t (:bold t :foreground "Red" :weight bold :height 1.05))))
     (egg-warning ((t (:bold t :foreground "Red" :weight bold))))
     (eldoc-highlight-function-argument ((t (:bold t :weight bold))))
     (epa-field-body ((t (:italic t :slant italic))))
     (epa-field-name ((t (:bold t :weight bold))))
     (epa-mark ((t (:bold t :foreground "red" :weight bold))))
     (epa-string ((t (:foreground "blue4"))))
     (epa-validity-disabled ((t (:italic t :slant italic))))
     (epa-validity-high ((t (:bold t :weight bold))))
     (epa-validity-low ((t (:italic t :slant italic))))
     (epa-validity-medium ((t (:italic t :slant italic))))
     (erc-action-face ((t (:bold t :weight bold))))
     (erc-bold-face ((t (:bold t :weight bold))))
     (erc-button ((t (:bold t :weight bold))))
     (erc-chanlist-even-line-face ((t (:inverse-video nil))))
     (erc-chanlist-header-face ((t (:bold t :weight bold))))
     (erc-chanlist-highlight ((t (:foreground "red"))))
     (erc-chanlist-odd-line-face ((t (nil))))
     (erc-command-indicator-face ((t (:bold t :weight bold))))
     (erc-current-nick-face ((t (:bold t :foreground "DarkTurquoise" :weight bold))))
     (erc-dangerous-host-face ((t (:foreground "red"))))
     (erc-default-face ((t (nil))))
     (erc-direct-msg-face ((t (:foreground "IndianRed"))))
     (erc-error-face ((t (:foreground "red"))))
     (erc-fool-face ((t (:foreground "dim gray"))))
     (erc-header-line ((t (:background "grey90" :foreground "grey20"))))
     (erc-input-face ((t (:foreground "brown"))))
     (erc-inverse-face ((t (:background "Black" :foreground "White"))))
     (erc-keyword-face ((t (:bold t :foreground "pale green" :weight bold))))
     (erc-my-nick-face ((t (:bold t :foreground "brown" :weight bold))))
     (erc-my-nick-prefix-face ((t (:bold t :inherit erc-nick-default-face :weight bold))))
     (erc-nick-default-face ((t (:bold t :weight bold))))
     (erc-nick-msg-face ((t (:bold t :foreground "IndianRed" :weight bold))))
     (erc-nick-prefix-face ((t (:bold t :inherit erc-nick-default-face :weight bold))))
     (erc-notice-face ((t (:bold t :foreground "SlateBlue" :weight bold))))
     (erc-pal-face ((t (:bold t :foreground "Magenta" :weight bold))))
     (erc-prompt-face ((t (:bold t :background "lightBlue2" :foreground "Black" :weight bold))))
     (erc-timestamp-face ((t (:foreground "black"))))
     (erc-underline-face ((t (:underline t))))
     (error ((t (:bold t :foreground "Pink" :weight bold))))
     (escape-glyph ((t (:foreground "brown"))))
     (eshell-ls-archive ((t (:bold t :foreground "Orchid" :weight bold))))
     (eshell-ls-backup ((t (:foreground "OrangeRed"))))
     (eshell-ls-clutter ((t (:bold t :foreground "OrangeRed" :weight bold))))
     (eshell-ls-directory ((t (:bold t :foreground "Blue" :weight bold))))
     (eshell-ls-executable ((t (:bold t :foreground "ForestGreen" :weight bold))))
     (eshell-ls-missing ((t (:bold t :foreground "Red" :weight bold))))
     (eshell-ls-product ((t (:foreground "OrangeRed"))))
     (eshell-ls-readonly ((t (:foreground "Brown"))))
     (eshell-ls-special ((t (:bold t :foreground "Magenta" :weight bold))))
     (eshell-ls-symlink ((t (:bold t :foreground "Dark Cyan" :weight bold))))
     (eshell-ls-unreadable ((t (:foreground "Grey30"))))
     (eshell-prompt ((t (:bold t :foreground "Red" :weight bold))))
     (evil-ex-commands ((t (:italic t :underline t :slant italic))))
     (evil-ex-info ((t (:italic t :foreground "red" :slant italic))))
     (evil-ex-lazy-highlight ((t (:inherit lazy-highlight))))
     (evil-ex-search ((t (:inherit isearch))))
     (evil-ex-substitute-matches ((t (:inherit lazy-highlight))))
     (evil-ex-substitute-replacement ((t (:foreground "red" :underline t))))
     (ffap ((t (:background "darkseagreen2"))))
     (fg:erc-color-face0 ((t (:foreground "White"))))
     (fg:erc-color-face1 ((t (:foreground "black"))))
     (fg:erc-color-face10 ((t (:foreground "lightblue1"))))
     (fg:erc-color-face11 ((t (:foreground "cyan"))))
     (fg:erc-color-face12 ((t (:foreground "blue"))))
     (fg:erc-color-face13 ((t (:foreground "deeppink"))))
     (fg:erc-color-face14 ((t (:foreground "gray50"))))
     (fg:erc-color-face15 ((t (:foreground "gray90"))))
     (fg:erc-color-face2 ((t (:foreground "blue4"))))
     (fg:erc-color-face3 ((t (:foreground "green4"))))
     (fg:erc-color-face4 ((t (:foreground "red"))))
     (fg:erc-color-face5 ((t (:foreground "brown"))))
     (fg:erc-color-face6 ((t (:foreground "purple"))))
     (fg:erc-color-face7 ((t (:foreground "orange"))))
     (fg:erc-color-face8 ((t (:foreground "yellow"))))
     (fg:erc-color-face9 ((t (:foreground "green"))))
     (file-name-shadow ((t (:foreground "grey50"))))
     (fixed-pitch ((t (:family "Monospace"))))
     (fixed-pitch-serif ((t (:family "Monospace Serif"))))
     (flyspell-duplicate ((t (:bold t :foreground "Gold3" :underline t :weight bold))))
     (flyspell-incorrect ((t (:bold t :foreground "OrangeRed" :underline t :weight bold))))
     (font-lock-artbollocks-face ((t (:bold t :stipple nil :background "White" :foreground "Purple" :inverse-video nil :underline t :slant normal :weight bold))))
     (font-lock-builtin-face ((t (:foreground "purple"))))
     (font-lock-comment-delimiter-face ((t (:foreground "blue"))))
     (font-lock-comment-face ((t (:foreground "blue"))))
     (font-lock-constant-face ((t (:foreground "green4"))))
     (font-lock-doc-face ((t (:background "#f2f2f2"))))
     (font-lock-function-name-face ((t (:bold t :background "moccasin" :foreground "#008b8b" :weight bold))))
     (font-lock-keyword-face ((t (:bold t :foreground "#a52a2a" :weight bold))))
     (font-lock-lexical-illusions-face ((t (:bold t :stipple nil :background "magenta" :foreground "black" :inverse-video nil :underline t :slant normal :weight bold))))
     (font-lock-negation-char-face ((t (nil))))
     (font-lock-passive-voice-face ((t (:bold t :stipple nil :background "White" :foreground "Gray" :inverse-video nil :underline t :slant normal :weight bold))))
     (font-lock-preprocessor-face ((t (:foreground "purple"))))
     (font-lock-regexp-grouping-backslash ((t (:bold t :weight bold))))
     (font-lock-regexp-grouping-construct ((t (:bold t :weight bold))))
     (font-lock-storage-keyword-face ((t (:bold t :foreground "seagreen" :weight bold))))
     (font-lock-string-face ((t (:background "#f2f2f2" :foreground "#ff00ff"))))
     (font-lock-type-face ((t (:bold t :foreground "ForestGreen" :weight bold))))
     (font-lock-variable-name-face ((t (:bold t :background "#D87ED710D87E" :foreground "#5B48094050D9" :weight bold))))
     (font-lock-warning-face ((t (:bold t :foreground "Red" :weight bold))))
     (font-lock-weasel-words-face ((t (:bold t :stipple nil :background "White" :foreground "Brown" :inverse-video nil :underline t :slant normal :weight bold))))
     (fringe ((t (:background "#e5e5e5"))))
     (glyphless-char ((t (:inherit underline))))
     (gnus-group-mail-1 ((t (:bold t :foreground "DeepPink3" :weight bold))))
     (gnus-group-mail-1-empty ((t (:foreground "DeepPink3"))))
     (gnus-group-mail-2 ((t (:bold t :foreground "HotPink3" :weight bold))))
     (gnus-group-mail-2-empty ((t (:foreground "HotPink3"))))
     (gnus-group-mail-3 ((t (:bold t :foreground "magenta4" :weight bold))))
     (gnus-group-mail-3-empty ((t (:foreground "magenta4"))))
     (gnus-group-mail-low ((t (:bold t :foreground "DeepPink4" :weight bold))))
     (gnus-group-mail-low-empty ((t (:foreground "DeepPink4"))))
     (gnus-group-news-1 ((t (:bold t :foreground "ForestGreen" :weight bold))))
     (gnus-group-news-1-empty ((t (:foreground "ForestGreen"))))
     (gnus-group-news-2 ((t (:bold t :foreground "CadetBlue4" :weight bold))))
     (gnus-group-news-2-empty ((t (:foreground "CadetBlue4"))))
     (gnus-group-news-3 ((t (:bold t :weight bold))))
     (gnus-group-news-3-empty ((t (nil))))
     (gnus-group-news-4 ((t (:bold t :weight bold))))
     (gnus-group-news-4-empty ((t (nil))))
     (gnus-group-news-5 ((t (:bold t :weight bold))))
     (gnus-group-news-5-empty ((t (nil))))
     (gnus-group-news-6 ((t (:bold t :weight bold))))
     (gnus-group-news-6-empty ((t (nil))))
     (gnus-group-news-low ((t (:bold t :foreground "DarkGreen" :weight bold))))
     (gnus-group-news-low-empty ((t (:foreground "DarkGreen"))))
     (gnus-splash ((t (:foreground "#888888"))))
     (gnus-summary-cancelled ((t (:background "black" :foreground "yellow"))))
     (gnus-summary-high-ancient ((t (:bold t :foreground "RoyalBlue" :weight bold))))
     (gnus-summary-high-read ((t (:bold t :foreground "DarkGreen" :weight bold))))
     (gnus-summary-high-ticked ((t (:bold t :foreground "firebrick" :weight bold))))
     (gnus-summary-high-undownloaded ((t (:bold t :foreground "cyan4" :weight bold))))
     (gnus-summary-high-unread ((t (:bold t :weight bold))))
     (gnus-summary-low-ancient ((t (:italic t :foreground "RoyalBlue" :slant italic))))
     (gnus-summary-low-read ((t (:italic t :foreground "DarkGreen" :slant italic))))
     (gnus-summary-low-ticked ((t (:italic t :foreground "firebrick" :slant italic))))
     (gnus-summary-low-undownloaded ((t (:italic t :foreground "cyan4" :slant italic :weight normal))))
     (gnus-summary-low-unread ((t (:italic t :slant italic))))
     (gnus-summary-normal-ancient ((t (:foreground "RoyalBlue"))))
     (gnus-summary-normal-read ((t (:foreground "DarkGreen"))))
     (gnus-summary-normal-ticked ((t (:foreground "firebrick"))))
     (gnus-summary-normal-undownloaded ((t (:foreground "cyan4" :weight normal))))
     (gnus-summary-normal-unread ((t (nil))))
     (gnus-summary-selected ((t (:underline t))))
     (header-line ((t (:background "grey90" :foreground "grey20"))))
     (header-line-highlight ((t (:inherit highlight))))
     (help-argument-name ((t (:italic t :slant italic))))
     (hexl-address-region ((t (:inherit header-line))))
     (hexl-ascii-region ((t (:inherit header-line))))
     (hide-ifdef-shadow ((t (:inherit shadow))))
     (highlight ((t (:background "darkseagreen2"))))
     (hl-line ((t (:background "darkseagreen2"))))
     (holiday ((t (:background "pink"))))
     (homoglyph ((t (:foreground "black"))))
     (howm-menu-key-face ((t (:foreground "dark red"))))
     (howm-menu-list-face ((t (nil))))
     (howm-mode-keyword-face ((t (:background "blue" :foreground "white"))))
     (howm-mode-ref-face ((t (:foreground "blue"))))
     (howm-mode-title-face ((t (:foreground "RoyalBlue"))))
     (howm-mode-wiki-face ((t (:foreground "blue"))))
     (howm-reminder-deadline-face ((t (:foreground "red"))))
     (howm-reminder-defer-face ((t (:foreground "magenta"))))
     (howm-reminder-done-face ((t (nil))))
     (howm-reminder-normal-face ((t (:foreground "blue"))))
     (howm-reminder-schedule-face ((t (:foreground "dark green"))))
     (howm-reminder-today-face ((t (:background "orange" :foreground "black"))))
     (howm-reminder-todo-face ((t (:foreground "purple"))))
     (howm-reminder-tomorrow-face ((t (:background "pink" :foreground "black"))))
     (howm-view-empty-face ((t (:background "midnight blue"))))
     (howm-view-hilit-face ((t (:foreground "red"))))
     (howm-view-name-face ((t (:background "blue" :foreground "white"))))
     (icicle-Completions-instruction-1 ((t (:foreground "Blue"))))
     (icicle-Completions-instruction-2 ((t (:foreground "Red"))))
     (icicle-candidate-part ((t (:background "#EF84FFEAF427"))))
     (icicle-common-match-highlight-Completions ((t (:foreground "magenta3"))))
     (icicle-complete-input ((t (:foreground "DarkGreen"))))
     (icicle-completing-mustmatch-prompt-prefix ((t (nil))))
     (icicle-completing-prompt-prefix ((t (nil))))
     (icicle-completion ((t (:foreground "Red"))))
     (icicle-current-candidate-highlight ((t (:background "CadetBlue1"))))
     (icicle-extra-candidate ((t (:background "#C847D8FEFFFF"))))
     (icicle-historical-candidate ((t (:foreground "Blue"))))
     (icicle-input-completion-fail ((t (:background "Plum" :foreground "Black"))))
     (icicle-input-completion-fail-lax ((t (:background "#FFFFB8C4BB87" :foreground "Black"))))
     (icicle-match-highlight-Completions ((t (:foreground "Red3"))))
     (icicle-match-highlight-minibuffer ((t (:underline t))))
     (icicle-mode-line-help ((t (:foreground "Blue"))))
     (icicle-multi-command-completion ((t (:background "#78F6FFFF8E4F" :foreground "Red"))))
     (icicle-mustmatch-completion ((t (:box (:line-width -2 :color "Blue")))))
     (icicle-prompt-suffix ((t (nil))))
     (icicle-proxy-candidate ((t (:background "#E1E1EAEAFFFF" :box (:line-width 2 :color "White" :style released-button)))))
     (icicle-saved-candidate ((t (:background "gray80"))))
     (icicle-search-context-level-1 ((t (:background "#FFFFBE3DFFFF"))))
     (icicle-search-context-level-2 ((t (:background "#BE3DFFFFBE3D"))))
     (icicle-search-context-level-3 ((t (:background "#BE3DBE3DFFFF"))))
     (icicle-search-context-level-4 ((t (:background "#FFFFFFFFBE3D"))))
     (icicle-search-context-level-5 ((t (:background "#F7F7D7D7FFFF"))))
     (icicle-search-context-level-6 ((t (:background "#D7D7FFFFE7E6"))))
     (icicle-search-context-level-7 ((t (:background "#D7D7E7E6FFFF"))))
     (icicle-search-context-level-8 ((t (:background "#F7F7FFFFD7D7"))))
     (icicle-search-current-input ((t (:background "Green" :foreground "Black"))))
     (icicle-search-main-regexp-current ((t (:background "misty rose"))))
     (icicle-search-main-regexp-others ((t (:background "CadetBlue1"))))
     (icicle-special-candidate ((t (:background "#DB17FFF4E581"))))
     (icicle-whitespace-highlight ((t (:background "Magenta"))))
     (info-command-ref-item ((t (:background "LightGray" :foreground "Blue"))))
     (info-file ((t (:background "LightGray" :foreground "Blue"))))
     (info-function-ref-item ((t (:background "LightGray" :foreground "DarkBlue"))))
     (info-header-node ((t (nil))))
     (info-header-xref ((t (nil))))
     (info-index-match ((t (:inherit match))))
     (info-macro-ref-item ((t (:background "LightGray" :foreground "DarkMagenta"))))
     (info-menu ((t (:foreground "Blue"))))
     (info-menu-header ((t (:bold t :weight bold))))
     (info-menu-star ((t (:foreground "red1"))))
     (info-node ((t (:italic t :bold t :foreground "brown" :slant italic :weight bold))))
     (info-quoted-name ((t (:background "#f2f2f2" :foreground "DarkViolet"))))
     (info-reference-item ((t (:background "LightGray"))))
     (info-single-quote ((t (:bold t :foreground "Magenta" :weight bold))))
     (info-special-form-ref-item ((t (:background "LightGray" :foreground "DarkMagenta"))))
     (info-string ((t (:background "#f2f2f2" :foreground "red3"))))
     (info-syntax-class-item ((t (:background "LightGray" :foreground "DarkGreen"))))
     (info-title-1 ((t (:bold t :weight bold :height 1.3))))
     (info-title-2 ((t (:bold t :weight bold :height 1.2))))
     (info-title-3 ((t (:bold t :weight bold :height 1.1))))
     (info-title-4 ((t (:bold t :weight bold))))
     (info-user-option-ref-item ((t (:background "LightGray" :foreground "Red"))))
     (info-variable-ref-item ((t (:background "LightGray" :foreground "FireBrick"))))
     (info-xref ((t (:bold t :foreground "magenta4" :weight bold))))
     (info-xref-visited ((t (:foreground "magenta4" :underline t))))
     (internal-border ((t (nil))))
     (isearch ((t (:background "#F952FBFBC332"))))
     (isearch-fail ((t (:background "RosyBrown1"))))
     (italic ((t (:italic t :slant italic))))
     (lazy-highlight ((t (:background "paleturquoise"))))
     (line-number ((t (:inherit (shadow default)))))
     (line-number-current-line ((t (:inherit line-number))))
     (link ((t (:foreground "blue1" :underline t))))
     (link-visited ((t (:foreground "magenta4" :underline t))))
     (linkd-command ((t (:foreground "red" :underline t))))
     (linkd-generic-link ((t (:foreground "blue"))))
     (linkd-generic-link-name ((t (:foreground "blue"))))
     (linkd-icon ((t (:underline nil))))
     (linkd-star ((t (:foreground "unspecified-bg"))))
     (linkd-star-name ((t (:background "Pink" :foreground "blue"))))
     (linkd-tag ((t (:foreground "unspecified-bg"))))
     (linkd-tag-name ((t (:foreground "blue" :underline t))))
     (linkd-wiki ((t (:foreground "FireBrick" :underline t))))
     (log-edit-header ((t (:bold t :foreground "#a52a2a" :weight bold))))
     (log-edit-summary ((t (:foreground "#008b8b"))))
     (log-edit-unknown-header ((t (:foreground "blue"))))
     (log-view-file ((t (:bold t :background "grey70" :weight bold))))
     (log-view-message ((t (:background "grey85"))))
     (makefile-makepp-perl ((t (:background "LightBlue1"))))
     (makefile-shell ((t (nil))))
     (makefile-space ((t (:background "hotpink"))))
     (makefile-targets ((t (:foreground "#008b8b"))))
     (markdown-blockquote-face ((t (:background "#f2f2f2"))))
     (markdown-bold-face ((t (:bold t :foreground "#008b8b" :weight bold))))
     (markdown-comment-face ((t (:foreground "blue"))))
     (markdown-header-face ((t (:bold t :foreground "#008b8b" :weight bold))))
     (markdown-header-face-1 ((t (:bold t :foreground "#008b8b" :weight bold))))
     (markdown-header-face-2 ((t (:bold t :foreground "#008b8b" :weight bold))))
     (markdown-header-face-3 ((t (:bold t :foreground "#008b8b" :weight bold))))
     (markdown-header-face-4 ((t (:bold t :foreground "#008b8b" :weight bold))))
     (markdown-header-face-5 ((t (:bold t :foreground "#008b8b" :weight bold))))
     (markdown-header-face-6 ((t (:bold t :foreground "#008b8b" :weight bold))))
     (markdown-inline-code-face ((t (:foreground "green4"))))
     (markdown-italic-face ((t (:italic t :foreground "#008b8b" :slant italic))))
     (markdown-link-face ((t (:bold t :foreground "#a52a2a" :weight bold))))
     (markdown-link-title-face ((t (:foreground "blue"))))
     (markdown-list-face ((t (:foreground "purple"))))
     (markdown-math-face ((t (:background "#f2f2f2" :foreground "#ff00ff"))))
     (markdown-missing-link-face ((t (:bold t :foreground "Red" :weight bold))))
     (markdown-pre-face ((t (:foreground "green4"))))
     (markdown-reference-face ((t (:bold t :foreground "ForestGreen" :weight bold))))
     (markdown-url-face ((t (:background "#f2f2f2" :foreground "#ff00ff"))))
     (match ((t (:foreground "Red3"))))
     (menu ((t (nil))))
     (message-cited-text ((t (:foreground "red"))))
     (message-header-cc ((t (:foreground "MidnightBlue"))))
     (message-header-name ((t (:foreground "cornflower blue"))))
     (message-header-newsgroups ((t (:italic t :bold t :foreground "blue4" :slant italic :weight bold))))
     (message-header-other ((t (:foreground "steel blue"))))
     (message-header-subject ((t (:bold t :foreground "navy blue" :weight bold))))
     (message-header-to ((t (:bold t :foreground "MidnightBlue" :weight bold))))
     (message-header-xheader ((t (:foreground "blue"))))
     (message-mml ((t (:foreground "ForestGreen"))))
     (message-separator ((t (:foreground "brown"))))
     (minibuffer-prompt ((t (:foreground "dark blue"))))
     (mm/bold ((t (:bold t :weight extra-bold))))
     (mm/condition ((t (:background "#CB98E699EAF9" :strike-through nil))))
     (mm/consequent ((t (:background "#E544E5E5D570"))))
     (mm/otherwise ((t (:background "#DAFDDB96CBDD"))))
     (mode-line ((t (:background "grey75" :foreground "black"))))
     (mode-line-buffer-id ((t (:bold t :weight bold))))
     (mode-line-emphasis ((t (:bold t :weight bold))))
     (mode-line-highlight ((t (:box (:line-width 2 :color "grey40" :style released-button)))))
     (mode-line-inactive ((t (:background "grey90" :foreground "grey20" :box (:line-width -1 :color "grey75" :style nil) :weight light))))
     (mouse ((t (:background "#000000"))))
     (mouse-drag-and-drop-region ((t (:inherit region))))
     (next-error ((t (:background "lightgoldenrod2"))))
     (nobreak-hyphen ((t (:foreground "cyan"))))
     (nobreak-space ((t (:foreground "brown" :underline t))))
     (nxml-attribute-colon ((t (nil))))
     (nxml-attribute-local-name ((t (:foreground "#008b8b"))))
     (nxml-attribute-prefix ((t (:foreground "purple"))))
     (nxml-attribute-value ((t (:background "#f2f2f2" :foreground "#ff00ff"))))
     (nxml-attribute-value-delimiter ((t (:background "#f2f2f2" :foreground "#ff00ff"))))
     (nxml-cdata-section-CDATA ((t (:foreground "purple"))))
     (nxml-cdata-section-content ((t (nil))))
     (nxml-cdata-section-delimiter ((t (nil))))
     (nxml-char-ref-delimiter ((t (:foreground "green4"))))
     (nxml-char-ref-number ((t (:foreground "green4"))))
     (nxml-comment-content ((t (:foreground "blue"))))
     (nxml-comment-delimiter ((t (:foreground "blue"))))
     (nxml-delimited-data ((t (:background "#f2f2f2"))))
     (nxml-delimiter ((t (nil))))
     (nxml-element-colon ((t (nil))))
     (nxml-element-local-name ((t (:foreground "#008b8b"))))
     (nxml-element-prefix ((t (:foreground "purple"))))
     (nxml-entity-ref-delimiter ((t (:foreground "green4"))))
     (nxml-entity-ref-name ((t (:foreground "green4"))))
     (nxml-glyph ((t (:background "light grey" :foreground "black" :slant normal :weight normal))))
     (nxml-hash ((t (:foreground "purple"))))
     (nxml-heading ((t (:bold t :weight bold))))
     (nxml-markup-declaration-delimiter ((t (nil))))
     (nxml-name ((t (:foreground "purple"))))
     (nxml-namespace-attribute-colon ((t (nil))))
     (nxml-namespace-attribute-prefix ((t (:foreground "#008b8b"))))
     (nxml-namespace-attribute-value ((t (:background "#f2f2f2" :foreground "#ff00ff"))))
     (nxml-namespace-attribute-value-delimiter ((t (:background "#f2f2f2" :foreground "#ff00ff"))))
     (nxml-namespace-attribute-xmlns ((t (:foreground "purple"))))
     (nxml-outline-active-indicator ((t (:inherit nxml-outline-indicator :box 1))))
     (nxml-outline-ellipsis ((t (:bold t :inherit default :weight bold))))
     (nxml-outline-indicator ((t (:inherit default))))
     (nxml-processing-instruction-content ((t (:background "#f2f2f2"))))
     (nxml-processing-instruction-delimiter ((t (nil))))
     (nxml-processing-instruction-target ((t (:bold t :foreground "#a52a2a" :weight bold))))
     (nxml-prolog-keyword ((t (:bold t :foreground "#a52a2a" :weight bold))))
     (nxml-prolog-literal-content ((t (:background "#f2f2f2"))))
     (nxml-prolog-literal-delimiter ((t (:background "#f2f2f2"))))
     (nxml-ref ((t (:foreground "green4"))))
     (nxml-tag-delimiter ((t (nil))))
     (nxml-tag-slash ((t (nil))))
     (nxml-text ((t (nil))))
     (org-agenda-calendar-event ((t (:inherit default))))
     (org-agenda-calendar-sexp ((t (:inherit default))))
     (org-agenda-clocking ((t (:inherit secondary-selection :background "yellow"))))
     (org-agenda-column-dateline ((t (:inherit org-column))))
     (org-agenda-current-time ((t (:inherit org-time-grid :foreground "DarkGoldenrod"))))
     (org-agenda-date ((t (:bold t :inherit org-agenda-structure :foreground "blue" :weight bold))))
     (org-agenda-date-today ((t (:italic t :bold t :inherit org-agenda-date :foreground "blue" :box (:line-width 2 :color "grey55" :style pressed-button) :slant italic :weight bold))))
     (org-agenda-date-weekend ((t (:bold t :inherit org-agenda-date :foreground "blue" :weight bold))))
     (org-agenda-diary ((t (:inherit default))))
     (org-agenda-dimmed-todo-face ((t (:foreground "grey50"))))
     (org-agenda-done ((t (:foreground "DarkGreen" :strike-through t))))
     (org-agenda-filter-category ((t (:background "grey75" :foreground "black"))))
     (org-agenda-filter-effort ((t (:inherit mode-line))))
     (org-agenda-filter-regexp ((t (:inherit mode-line))))
     (org-agenda-filter-tags ((t (:background "grey75" :foreground "black"))))
     (org-agenda-restriction-lock ((t (:background "yellow1"))))
     (org-agenda-structure ((t (:bold t :foreground "blue" :weight bold))))
     (org-archived ((t (:foreground "green"))))
     (org-block ((t (:foreground "grey50"))))
     (org-block-background ((t (nil))))
     (org-block-begin-line ((t (:inherit org-meta-line :foreground "blue"))))
     (org-block-end-line ((t (:inherit org-meta-line :foreground "blue"))))
     (org-checkbox ((t (:bold t :weight bold))))
     (org-checkbox-statistics-done ((t (:inherit org-done :foreground "ForestGreen"))))
     (org-checkbox-statistics-todo ((t (:bold t :inherit org-todo :foreground "Red1" :weight bold))))
     (org-clock-overlay ((t (:background "yellow1"))))
     (org-code ((t (:foreground "grey50"))))
     (org-column ((t (:background "grey90" :strike-through nil :underline nil :slant normal :weight normal))))
     (org-column-title ((t (:bold t :background "grey90" :underline t :weight bold))))
     (org-date ((t (:foreground "Purple" :underline t))))
     (org-date-selected ((t (:background "Red1"))))
     (org-default ((t (:inherit default))))
     (org-document-info ((t (:foreground "midnight blue"))))
     (org-document-info-keyword ((t (:foreground "grey50"))))
     (org-document-title ((t (:bold t :foreground "midnight blue" :weight bold :height 1.2))))
     (org-done ((t (:foreground "ForestGreen"))))
     (org-drawer ((t (:bold t :foreground "blue" :weight bold))))
     (org-ellipsis ((t (:foreground "DarkGoldenrod" :underline t))))
     (org-footnote ((t (:foreground "Purple" :underline t))))
     (org-formula ((t (:foreground "Firebrick"))))
     (org-habit-alert-face ((t (:background "#f5f946"))))
     (org-habit-alert-future-face ((t (:background "#fafca9"))))
     (org-habit-clear-face ((t (:background "#8270f9"))))
     (org-habit-clear-future-face ((t (:background "#d6e4fc"))))
     (org-habit-overdue-face ((t (:background "#f9372d"))))
     (org-habit-overdue-future-face ((t (:background "#fc9590"))))
     (org-habit-ready-face ((t (:background "#4df946"))))
     (org-habit-ready-future-face ((t (:background "#acfca9"))))
     (org-headline-done ((t (:foreground "RosyBrown"))))
     (org-hide ((t (:foreground "gray90"))))
     (org-latex-and-export-specials ((t (:foreground "SaddleBrown"))))
     (org-latex-and-related ((t (:foreground "burlywood"))))
     (org-level-1 ((t (:bold t :foreground "Blue1" :weight bold))))
     (org-level-2 ((t (:foreground "DarkGoldenrod4"))))
     (org-level-3 ((t (:foreground "Purple"))))
     (org-level-4 ((t (:foreground "Firebrick"))))
     (org-level-5 ((t (:foreground "ForestGreen"))))
     (org-level-6 ((t (:foreground "CadetBlue"))))
     (org-level-7 ((t (:foreground "Orchid"))))
     (org-level-8 ((t (:foreground "RosyBrown"))))
     (org-link ((t (:foreground "Purple" :underline t))))
     (org-list-dt ((t (:bold t :weight bold))))
     (org-macro ((t (:inherit org-latex-and-related))))
     (org-meta-line ((t (:foreground "blue"))))
     (org-mode-line-clock ((t (:inherit modeline :background "grey75" :foreground "black"))))
     (org-mode-line-clock-overrun ((t (:inherit modeline :background "red" :foreground "black"))))
     (org-priority ((t (:inherit font-lock-keyword-face))))
     (org-property-value ((t (nil))))
     (org-quote ((t (:inherit org-block :foreground "grey50"))))
     (org-scheduled ((t (:foreground "DarkGreen"))))
     (org-scheduled-previously ((t (:foreground "DarkGreen"))))
     (org-scheduled-today ((t (:foreground "DarkGreen"))))
     (org-sexp-date ((t (:foreground "Purple"))))
     (org-special-keyword ((t (:foreground "RosyBrown"))))
     (org-table ((t (:foreground "Blue1"))))
     (org-tag ((t (:bold t :weight bold))))
     (org-tag-group ((t (:inherit org-tag))))
     (org-target ((t (:underline t))))
     (org-time-grid ((t (:foreground "DarkGoldenrod"))))
     (org-todo ((t (:bold t :foreground "Red1" :weight bold))))
     (org-upcoming-deadline ((t (:foreground "Firebrick"))))
     (org-verbatim ((t (:foreground "grey50"))))
     (org-verse ((t (:inherit org-block :foreground "grey50"))))
     (org-warning ((t (:bold t :foreground "Red1" :weight bold))))
     (outline-1 ((t (:foreground "#008b8b"))))
     (outline-2 ((t (:foreground "#008b8b"))))
     (outline-3 ((t (:bold t :foreground "#a52a2a" :weight bold))))
     (outline-4 ((t (:foreground "purple"))))
     (outline-5 ((t (:foreground "blue"))))
     (outline-6 ((t (:foreground "green4"))))
     (outline-7 ((t (:bold t :foreground "ForestGreen" :weight bold))))
     (outline-8 ((t (:background "#f2f2f2" :foreground "#ff00ff"))))
     (package-description ((t (:inherit default))))
     (package-help-section-name ((t (:inherit (bold font-lock-function-name-face)))))
     (package-name ((t (:inherit link))))
     (package-status-avail-obso ((t (:inherit package-status-incompat))))
     (package-status-available ((t (:inherit default))))
     (package-status-built-in ((t (:inherit font-lock-builtin-face))))
     (package-status-dependency ((t (:inherit package-status-installed))))
     (package-status-disabled ((t (:inherit font-lock-warning-face))))
     (package-status-external ((t (:inherit package-status-built-in))))
     (package-status-held ((t (:inherit font-lock-constant-face))))
     (package-status-incompat ((t (:inherit error))))
     (package-status-installed ((t (:inherit font-lock-comment-face))))
     (package-status-new ((t (:inherit (bold package-status-available)))))
     (package-status-unsigned ((t (:inherit font-lock-warning-face))))
     (query-replace ((t (:background "magenta4" :foreground "lightskyblue1"))))
     (quote ((t (:foreground "gray"))))
     (read-multiple-choice-face ((t (:bold t :inherit underline :weight bold))))
     (rectangle-preview ((t (:inherit region))))
     (region ((t (:background "lightgoldenrod2"))))
     (rng-error ((t (:inherit font-lock-warning-face))))
     (rpm-spec-dir-face ((t (:foreground "green"))))
     (rpm-spec-doc-face ((t (:foreground "magenta"))))
     (rpm-spec-ghost-face ((t (:foreground "red"))))
     (rpm-spec-macro-face ((t (:foreground "purple"))))
     (rpm-spec-package-face ((t (:foreground "red"))))
     (rpm-spec-tag-face ((t (:foreground "blue"))))
     (scroll-bar ((t (:background "grey75" :foreground "#000000"))))
     (secondary-selection ((t (:background "#E653E653BC77"))))
     (sgml-namespace ((t (:foreground "purple"))))
     (sh-escaped-newline ((t (:background "#f2f2f2" :foreground "#ff00ff"))))
     (sh-heredoc ((t (:foreground "#61EE1D540789"))))
     (sh-heredoc-face ((t (:foreground "#61EE1D540789"))))
     (sh-quoted-exec ((t (:foreground "magenta"))))
     (shadow ((t (:foreground "grey50"))))
     (show-paren-match ((t (:background "turquoise"))))
     (show-paren-match-expression ((t (:inherit show-paren-match))))
     (show-paren-mismatch ((t (:background "purple" :foreground "white"))))
     (sldb-catch-tag-face ((t (nil))))
     (sldb-condition-face ((t (nil))))
     (sldb-detailed-frame-line-face ((t (nil))))
     (sldb-frame-label-face ((t (nil))))
     (sldb-frame-line-face ((t (nil))))
     (sldb-local-name-face ((t (nil))))
     (sldb-local-value-face ((t (nil))))
     (sldb-non-restartable-frame-line-face ((t (nil))))
     (sldb-reference-face ((t (:underline t))))
     (sldb-restart-face ((t (nil))))
     (sldb-restart-number-face ((t (:bold t :weight bold))))
     (sldb-restart-type-face ((t (:bold t :foreground "#a52a2a" :weight bold))))
     (sldb-restartable-frame-line-face ((t (:foreground "lime green"))))
     (sldb-section-face ((t (nil))))
     (sldb-topline-face ((t (nil))))
     (slime-apropos-label ((t (:inherit italic))))
     (slime-apropos-symbol ((t (:inherit bold))))
     (slime-error-face ((t (:underline "red"))))
     (slime-highlight-edits-face ((t (:background "lightgray"))))
     (slime-highlight-face ((t (:background "darkseagreen2" :underline nil))))
     (slime-inspector-action-face ((t (:bold t :foreground "Red" :weight bold))))
     (slime-inspector-label-face ((t (:foreground "green4"))))
     (slime-inspector-topline-face ((t (nil))))
     (slime-inspector-type-face ((t (:foreground "ForestGreen"))))
     (slime-inspector-value-face ((t (:foreground "purple"))))
     (slime-note-face ((t (:underline "brown4"))))
     (slime-reader-conditional-face ((t (:foreground "blue"))))
     (slime-repl-input-face ((t (:bold t :weight bold))))
     (slime-repl-inputed-output-face ((t (:foreground "Red"))))
     (slime-repl-output-face ((t (:background "#f2f2f2" :foreground "#ff00ff"))))
     (slime-repl-output-mouseover-face ((t (:foreground "Red" :box (:line-width 1 :color "black" :style released-button)))))
     (slime-repl-prompt-face ((t (:bold t :foreground "#a52a2a" :weight bold))))
     (slime-repl-result-face ((t (nil))))
     (slime-style-warning-face ((t (:underline "brown"))))
     (slime-warning-face ((t (:underline "orange"))))
     (speedbar-button-face ((t (:foreground "green4"))))
     (speedbar-directory-face ((t (:foreground "blue4"))))
     (speedbar-file-face ((t (:foreground "cyan4"))))
     (speedbar-highlight-face ((t (:background "green"))))
     (speedbar-selected-face ((t (:foreground "red" :underline t))))
     (speedbar-separator-face ((t (:background "blue" :foreground "white" :overline "gray"))))
     (speedbar-tag-face ((t (:foreground "brown"))))
     (success ((t (:bold t :foreground "Green1" :weight bold))))
     (tool-bar ((t (:background "grey75" :foreground "black"))))
     (tooltip ((t (:background "lightyellow" :foreground "black"))))
     (trailing-whitespace ((t (:background "red"))))
     (tty-menu-disabled-face ((t (:background "blue" :foreground "lightgray"))))
     (tty-menu-enabled-face ((t (:bold t :background "blue" :foreground "yellow" :weight bold))))
     (tty-menu-selected-face ((t (:background "red"))))
     (tutorial-warning-face ((t (:bold t :foreground "Red" :weight bold))))
     (underline ((t (:underline t))))
     (undo-tree-visualizer-active-branch-face ((t (:bold t :foreground "black" :weight bold))))
     (undo-tree-visualizer-current-face ((t (:foreground "red"))))
     (undo-tree-visualizer-default-face ((t (:foreground "gray"))))
     (undo-tree-visualizer-register-face ((t (:foreground "yellow"))))
     (variable-pitch ((t (:family "arial"))))
     (vc-conflict-state ((t (:inherit vc-state-base))))
     (vc-edited-state ((t (:inherit vc-state-base))))
     (vc-locally-added-state ((t (:inherit vc-state-base))))
     (vc-locked-state ((t (:inherit vc-state-base))))
     (vc-missing-state ((t (:inherit vc-state-base))))
     (vc-needs-update-state ((t (:inherit vc-state-base))))
     (vc-removed-state ((t (:inherit vc-state-base))))
     (vc-state-base ((t (nil))))
     (vc-up-to-date-state ((t (:inherit vc-state-base))))
     (vertical-border ((t (nil))))
     (vline ((t (:background "light steel blue"))))
     (vline-visual ((t (:background "gray90"))))
     (w3m-anchor ((t (:foreground "blue"))))
     (w3m-arrived-anchor ((t (:foreground "navy"))))
     (w3m-bold ((t (:bold t :weight bold))))
     (w3m-current-anchor ((t (:bold t :underline t :weight bold))))
     (w3m-form ((t (:foreground "cyan" :underline t))))
     (w3m-form-button ((t (:background "lightgrey" :foreground "black" :box (:line-width 2 :style released-button)))))
     (w3m-form-button-mouse ((t (:background "DarkSeaGreen1" :foreground "black" :box (:line-width 2 :style released-button)))))
     (w3m-form-button-pressed ((t (:background "lightgrey" :foreground "black" :box (:line-width 2 :style pressed-button)))))
     (w3m-form-face ((t (:foreground "cyan" :underline t))))
     (w3m-header-line-location-content ((t (:background "Gray90" :foreground "DarkGoldenrod"))))
     (w3m-header-line-location-title ((t (:background "Gray90" :foreground "Blue"))))
     (w3m-history-current-url ((t (:background "cyan" :foreground "LightSkyBlue"))))
     (w3m-image ((t (:foreground "ForestGreen"))))
     (w3m-insert ((t (:foreground "purple"))))
     (w3m-italic ((t (:italic t :slant italic))))
     (w3m-strike-through ((t (:strike-through t))))
     (w3m-tab-background ((t (:background "LightSteelBlue" :foreground "black"))))
     (w3m-tab-mouse ((t (:background "Gray75" :foreground "white" :box (:line-width -1 :style released-button)))))
     (w3m-tab-selected ((t (:background "Gray85" :foreground "black" :box (:line-width -1 :style released-button)))))
     (w3m-tab-selected-background ((t (:background "LightSteelBlue" :foreground "black"))))
     (w3m-tab-selected-retrieving ((t (:background "Gray85" :foreground "red" :box (:line-width -1 :style released-button)))))
     (w3m-tab-unselected ((t (:background "Gray50" :foreground "Gray20" :box (:line-width -1 :style released-button)))))
     (w3m-tab-unselected-retrieving ((t (:background "Gray50" :foreground "OrangeRed" :box (:line-width -1 :style released-button)))))
     (w3m-tab-unselected-unseen ((t (:background "Gray70" :foreground "Gray20" :box (:line-width -1 :style released-button)))))
     (w3m-underline ((t (:underline t))))
     (warning ((t (:bold t :foreground "DarkOrange" :weight bold))))
     (wgrep-done-face ((t (:bold t :foreground "blue" :weight bold))))
     (wgrep-face ((t (:bold t :background "ForestGreen" :foreground "white" :weight bold))))
     (wgrep-file-face ((t (:bold t :background "ForestGreen" :foreground "white" :weight bold))))
     (wgrep-reject-face ((t (:bold t :foreground "red" :weight bold))))
     (widget-button ((t (:bold t :weight bold))))
     (widget-button-pressed ((t (:foreground "red"))))
     (widget-documentation ((t (:foreground "dark green"))))
     (widget-field ((t (:background "gray85"))))
     (widget-inactive ((t (:foreground "dim gray"))))
     (widget-single-line-field ((t (:background "gray85"))))
     (window-divider ((t (:foreground "gray60"))))
     (window-divider-first-pixel ((t (:foreground "gray80"))))
     (window-divider-last-pixel ((t (:foreground "gray40"))))
     (wl-highlight-action-argument-face ((t (:foreground "red"))))
     (wl-highlight-demo-face ((t (:background "#d9ffd9" :foreground "#006600"))))
     (wl-highlight-folder-closed-face ((t (:foreground "DarkOliveGreen4"))))
     (wl-highlight-folder-few-face ((t (:foreground "OrangeRed3"))))
     (wl-highlight-folder-killed-face ((t (:foreground "gray50"))))
     (wl-highlight-folder-many-face ((t (:foreground "tomato"))))
     (wl-highlight-folder-opened-face ((t (:foreground "ForestGreen"))))
     (wl-highlight-folder-path-face ((t (:bold t :underline t :weight bold))))
     (wl-highlight-folder-unknown-face ((t (:foreground "RoyalBlue"))))
     (wl-highlight-folder-unread-face ((t (:foreground "MediumVioletRed"))))
     (wl-highlight-folder-zero-face ((t (:foreground "BlueViolet"))))
     (wl-highlight-header-separator-face ((t (:background "DarkKhaki" :foreground "Black"))))
     (wl-highlight-logo-face ((t (:background "#d9ffd9" :foreground "SteelBlue"))))
     (wl-highlight-message-citation-header ((t (:foreground "DarkGreen"))))
     (wl-highlight-message-cited-text-1 ((t (:foreground "ForestGreen"))))
     (wl-highlight-message-cited-text-10 ((t (:foreground "wheat"))))
     (wl-highlight-message-cited-text-2 ((t (:foreground "violet"))))
     (wl-highlight-message-cited-text-3 ((t (:foreground "orchid3"))))
     (wl-highlight-message-cited-text-4 ((t (:foreground "purple1"))))
     (wl-highlight-message-cited-text-5 ((t (:foreground "MediumPurple1"))))
     (wl-highlight-message-cited-text-6 ((t (:foreground "PaleVioletRed"))))
     (wl-highlight-message-cited-text-7 ((t (:foreground "LightPink"))))
     (wl-highlight-message-cited-text-8 ((t (:foreground "salmon"))))
     (wl-highlight-message-cited-text-9 ((t (:foreground "SandyBrown"))))
     (wl-highlight-message-header-contents ((t (:bold t :foreground "purple" :weight bold))))
     (wl-highlight-message-headers ((t (:bold t :foreground "gray50" :weight bold))))
     (wl-highlight-message-important-header-contents ((t (:bold t :foreground "brown" :weight bold))))
     (wl-highlight-message-important-header-contents2 ((t (:bold t :foreground "DarkSlateBlue" :weight bold))))
     (wl-highlight-message-signature ((t (:foreground "DarkSlateBlue"))))
     (wl-highlight-message-unimportant-header-contents ((t (:bold t :foreground "DarkGreen" :weight bold))))
     (wl-highlight-summary-answered-face ((t (:foreground "khaki4"))))
     (wl-highlight-summary-copied-face ((t (:foreground "blue"))))
     (wl-highlight-summary-deleted-face ((t (:foreground "RoyalBlue4"))))
     (wl-highlight-summary-displaying-face ((t (:bold t :underline t :weight bold))))
     (wl-highlight-summary-disposed-face ((t (:foreground "DarkKhaki"))))
     (wl-highlight-summary-flagged-face ((t (:foreground "purple"))))
     (wl-highlight-summary-forwarded-face ((t (:foreground "DarkOliveGreen4"))))
     (wl-highlight-summary-high-read-face ((t (:bold t :foreground "SeaGreen" :weight bold))))
     (wl-highlight-summary-high-unread-face ((t (:bold t :foreground "tomato" :weight bold))))
     (wl-highlight-summary-important-flag-face ((t (:foreground "#FFFF45C50F28"))))
     (wl-highlight-summary-killed-face ((t (:foreground "LightSlateGray"))))
     (wl-highlight-summary-low-read-face ((t (:italic t :foreground "Green3" :slant italic))))
     (wl-highlight-summary-low-unread-face ((t (:italic t :foreground "RoyalBlue" :slant italic))))
     (wl-highlight-summary-new-face ((t (:foreground "tomato"))))
     (wl-highlight-summary-normal-face ((t (:foreground "SeaGreen"))))
     (wl-highlight-summary-prefetch-face ((t (:foreground "brown"))))
     (wl-highlight-summary-refiled-face ((t (:foreground "firebrick"))))
     (wl-highlight-summary-resend-face ((t (:foreground "orange3"))))
     (wl-highlight-summary-spam-face ((t (:foreground "LightSlateGray"))))
     (wl-highlight-summary-target-face ((t (:foreground "HotPink1"))))
     (wl-highlight-summary-temp-face ((t (:foreground "HotPink1"))))
     (wl-highlight-summary-thread-top-face ((t (:foreground "green4"))))
     (wl-highlight-summary-unread-face ((t (:foreground "RoyalBlue"))))
     (wl-highlight-thread-indent-face ((t (:foreground "gray40"))))
     (wl-message-header-narrowing-face ((t (:background "dark khaki" :foreground "black"))))
     (wl-summary-header-line ((t (:background "LavenderBlush2" :foreground "black"))))
     (wl-summary-header-line-folder ((t (:foreground "black"))))
     (wl-summary-header-line-from ((t (:bold t :foreground "DarkSlateBlue" :weight bold))))
     (wl-summary-header-line-subject ((t (:foreground "brown"))))
     (wl-summary-persistent-mark-face ((t (:foreground "SeaGreen1")))))))
(add-to-list 'color-themes '(my-color-theme  "THEME NAME" "YOUR NAME"))
