#!/bin/zsh
# $Xorg: xinitrc.cpp,v 1.3 2000/08/17 19:54:30 cpqbld Exp $

userresources="$HOME"/.Xresources
usermodmap="$HOME"/.Xmodmap
sysresources=/usr/X11R6/lib/X11/xinit/.Xresources
sysmodmap=/usr/X11R6/lib/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f "$sysresources" ]; then
    xrdb -merge "$sysresources"
fi

if [ -f "$sysmodmap" ]; then
    xmodmap "$sysmodmap"
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

echo "usermodemap=$usermodmap"
if [ -f "$usermodmap" ]; then
    echo "running it"
    xmodmap "$usermodmap"
else
    echo "not running it"
fi

setsid cygwinxhelper

# start some nice programs

echo HOME is $HOME >> /tmp/log
echo We are here >> /tmp/log
echo shell is $SHELL >> /tmp/log
env | grep XFILE >> /tmp/log
run xterm -ls 


