#!/bin/zsh
if [[ $OS == Windows_NT ]] ; then
    pskill -nobanner ssh-agent > /dev/null 2>&1
else
    killall ssh-agent >/dev/null 2>&1
    pkill ssh-agent >/dev/null 2>&1
fi

. =(setsid ssh-agent)

# below fixes wingit
if [[ $OS == Windows_NT ]] ; then
    SSH_AUTH_SOCK=$(cygpath -wm $SSH_AUTH_SOCK)
fi

echo "last_ssh_auth_sock=$SSH_AUTH_SOCK" > ~/.ssh_auth_sock

