#!/bin/zsh
if [[ $OS == Windows_NT ]] ; then
    pskill -nobanner ssh-agent > /dev/null
else
    killall ssh-agent
    pkill ssh-agent
fi

. =(setsid ssh-agent)

if [[ $OS == Windows_NT ]] ; then
    SSH_AUTH_SOCK=$(cygpath -wm $SSH_AUTH_SOCK)
fi

echo "last_ssh_auth_sock=$SSH_AUTH_SOCK" > ~/.ssh_auth_sock

