#!/bin/zsh

local zz=C:/Users/MMIKHA~1/AppData/Local/Temp/agent.$$$RANDOM
export SSH_AUTH_SOCK 
if [[ $OS == Windows_NT ]] ; then
    pskill64 -nobanner ssh-agent
else
    killall ssh-agent
fi

. <(ssh-agent -a $zz);
echo $zz
echo export SSH_AUTH_SOCK=$zz > ~/.ssh_auth_sock




