#!/bin/zsh
if [[ $OS == Windows_NT ]]
then
    pskill64 -nobanner ssh-agent > /dev/null
    SSH_AUTH_SOCK=$(cygpath -wm $SSH_AUTH_SOCK)
else
    killall ssh-agent
    pkill ssh-agent
fi

. =(setsid ssh-agent)

echo "export ssh_auth_sock=$SSH_AUTH_SOCK" > ~/.ssh_auth_sock

